package mcrtx.lod.format;

/**
 * Identity of the world a cache file describes.
 *
 * <p><b>A world is its seed and its dimension, not its folder.</b> The earlier
 * cache keyed itself on the save's location on disk, which is correct for a
 * private cache and fatal for a shareable one: the same world copied to another
 * machine, or entered through a different launcher instance, presents a
 * different path and its cache is rejected as belonging to something else. Seed
 * and dimension travel with the world, so a file baked by one player, produced
 * by a server, or generated by the offline tool is recognised by anyone else who
 * has that world.
 *
 * <p>The save folder's name is still worth keeping, but as a <em>label</em>
 * stored inside the file rather than as identity. It is what a person needs to
 * recognise a file; it is not what a program should compare.
 *
 * <p>Two worlds sharing a seed but not their edits -- a server and a
 * single-player copy of the same generation -- are deliberately treated as one
 * world. Their terrain agrees everywhere nobody has built, which is nearly
 * everywhere the distant field draws, and where they disagree
 * {@link LodProvenance} settles it by recency and source.
 */
public final class LodWorldId {
    /** Beta's dimension numbering. */
    public static final int DIMENSION_OVERWORLD = 0;
    public static final int DIMENSION_NETHER = -1;

    private final long seed;
    private final int dimension;

    public LodWorldId(long seed, int dimension) {
        this.seed = seed;
        this.dimension = dimension;
    }

    public long seed() {
        return seed;
    }

    public int dimension() {
        return dimension;
    }

    /**
     * File name for this world's tiles.
     *
     * <p>Derived only from identity, so the same world always produces the same
     * name and a shared file drops straight into another install's cache
     * directory. The seed is written as fixed-width hex rather than a decimal so
     * negative seeds do not need a sign and every name is the same length.
     */
    public String fileName() {
        StringBuilder name = new StringBuilder(32);
        name.append("lod-");
        appendHex64(name, seed);
        name.append(dimension < 0 ? "-dm" : "-d");
        name.append(Math.abs(dimension));
        name.append(".tiles");
        return name.toString();
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof LodWorldId)) {
            return false;
        }
        LodWorldId id = (LodWorldId) other;
        return seed == id.seed && dimension == id.dimension;
    }

    @Override
    public int hashCode() {
        return (int) (seed ^ (seed >>> 32)) * 31 + dimension;
    }

    @Override
    public String toString() {
        return "world(seed=" + seed + ", dim=" + dimension + ")";
    }

    private static void appendHex64(StringBuilder target, long value) {
        for (int shift = 60; shift >= 0; shift -= 4) {
            int nibble = (int) ((value >>> shift) & 0xF);
            target.append((char) (nibble < 10 ? ('0' + nibble) : ('a' + nibble - 10)));
        }
    }
}
